### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by hp9831g** [nblog/Vm2Import#1]
please provide full source code to automate it with x64dbg plugin for all the calls and jmp to obfuscated import calls.

thanks

**Comment by nblog** [comment]
method is not recommended. many reasons can make it impossible to determine whether it is a ".vmp" section. for example, when the memory is loaded with PE, it will only have a memory space.

**Comment by hp9831g** [comment]
sir, if possible, please provide source code, to expand its possibility, with other function, or use in a script dll.
thanks for replying.
