### ISSUE TITLE
emu status: false

### ISSUE THREAD

**Issue by herrblitzkrieg** [nblog/Vm2Import#4]
I did a right-click on VM_Start>Vm2Import>Fix Import Call Address......
![image](https://user-images.githubusercontent.com/65146766/170049504-7b62d20a-a727-4864-aa17-de5eb51c6f9b.png)

..... but why am I getting 'emu status: false' in the log section every time?
![image](https://user-images.githubusercontent.com/65146766/170050142-7052601d-c2c6-4be7-bdea-4db3c20cbb8b.png)

Additionally just FYI, first call actually points to CloseHandle API in kernel32.dll after passing through .vmp0 section:
![image](https://user-images.githubusercontent.com/65146766/170053006-31f685ab-c131-4791-bffa-19815f7e031d.png)

**Comment by nblog** [comment]
can samples be provided?
i've forgotten how it works 😱, I'll fix the code and open source it.

**Comment by herrblitzkrieg** [comment]
https://mega.nz/file/ev5jnJQD#kV44-T4mxFa_5n3Si4M56bUxPitQeGIkFNWZYQVplaI

**Comment by nblog** [comment]
@blitzkrieg99 [v2](https://github.com/nblog/Vm2Import/tree/v2), because vmp3.6 adds spoof "RET", caused me to write a lot of junk code, open source i will defer
